### ISSUE TITLE
NeedUserStoryTaskBreakdown

### ISSUE THREAD

**Issue by MegalodonInc** [testcrashandburn/Intro-to-SE-Group-6#16]
Since I am just joining the repo, I need to have a user story so that I can do the task breakdown for the user story. I would like to help set up Luca's sequence diagram.

**Comment by testcrashandburn** [comment]
Awesome, Mason is currently working on it, so pair with him and get the diagrams finished together.

**Comment by out-of-REM** [comment]
Diagrams were finished and all are available.
